export const ADD_TASK = "ADD_TASK"
export const DELETE_TASK = "DELETE_TASK"
export const SET_COMPLETE = "SET_COMPLETE"
export const SET_ONGOIN = "SET_ONGOIN"
export const SET_ASSIGNED = "SET_ASSIGNED"